# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IYXLEEpBekaUL4eqdwmVd5FVTO9sSEz
"""

import pandas as pd

phishing_keyword = ["urgent", "password reset", "bank", "verify", "account suspended"]


emails = pd.read_csv("/content/2409000762.csv")

if 'Content' in emails.columns:
    emails["is_pshishing"] = emails["Content"].apply(
        lambda x: any(keyword in str(x).lower() for keyword in phishing_keyword)
    )
    emails.to_csv("/content/Analysed_emails.csv", index=False)
    print("phishing detection complete")
else:
    print("ERROR: The 'content' column is missing from the dataset.")